Import the missing boto3 module
Without it, the lambda fails with the following error:
```
global name 'boto3' is not defined: NameError
Traceback (most recent call last):
File "/var/task/scheduler.py", line 38, in ccadb_import
kinto_pass = str(kms_decrypt_env("PROTECTED_KINTO_PASS"))
File "/var/task/scheduler.py", line 19, in kms_decrypt_env
return kms_decrypt(b64decode(os.environ[key]))
File "/var/task/scheduler.py", line 12, in kms_decrypt
res = boto3.client("kms").decrypt(
NameError: global name 'boto3' is not defined
```